baseURL = "https://www.niccari.net/"
languageCode = "ja-jp"
title = "niccari.net"
theme = "lekh"
publishDir = "docs"
canonifyurls = true

[params]
Name = "niccari.net"
About = "niccariによる、作ったアプリや技術記事などの活動をまとめたページです。"
Resume = ""
Email = ""
PostLimit = 3
favicon = "favicon.ico"
description = "Provides some visual, or utility web/mobile applications."
TwitterName = "niccari"

[[params.profiles]]
name = "GitHub"
url = "https://github.com/niccari"

[[params.profiles]]
name = "Twitter"
url = "https://twitter.com/niccari1"

[markup]
  [markup.highlight]
    lineNos = true

